#!/usr/bin/env python3
"""Generate zombie.json — a scratch-like save file (M40 flat single-stage shape).

A top-down zombie-survival demo built only from the engine's existing opcodes plus the two
small additions this build needs (mouse_down? and set_size — see scripts/interpreter.gd).
Ten zombie sprites stalk the player; the player shoots toward the cursor on mouse click and
each zombie carries a floating health bar that shrinks as it is shot.

The file is regenerated by this script rather than hand-edited: the ten zombies (and their ten
health bars) are near-identical, so authoring one and emitting it N times — the build_platformer.py
pattern — keeps the per-zombie logic (chase, separation, HP, bar) correct and in one place.

Design notes for the four behaviours this build adds:

  * Click to shoot. The player's fire loop only arms `fire_ready` while `mouse_down?` is held,
    repeating every FIRE_COOLDOWN — so bullets fire on click (held = auto-repeat) instead of
    continuously. Bullets still aim at the cursor (point towards mouse x/y).

  * Pause on hit. When a zombie reaches the player the player's hit handler sets the global
    `zombie_pause` for the duration of the knockback/blink, then clears it. Every zombie gates its
    movement on `zombie_pause == 0`, so the whole horde freezes for that moment.

  * No overlap. The platformer's revert-on-overlap pattern, applied both ways:
      - the player, after moving, reverts to its start-of-tick position if it ends up touching any
        zombie (so it can't walk *into* one);
      - a zombie, after advancing toward the player, first registers a hit (knockback throws the
        player clear) and then steps back out of the player, and also steps back out of any other
        zombie it overlaps — so zombies neither bury into the player nor stack on each other.

  * Health bars. Each zombie has HP (global, so a bullet can decrement the right zombie's HP
    deterministically) and publishes its position into globals each tick. A companion HealthBar
    sprite follows that position a few px above the zombie and uses set_size to draw a green bar
    whose width tracks the HP — parked off-screen with the zombie when it dies.
"""

import json

# ---- block builders (mirror PongScripts' / build_platformer's tiny helpers) ----

def hat(body):            return {"opcode": "when_flag_clicked", "inputs": {"body": body}}
def forever(body):        return {"opcode": "forever", "inputs": {"body": body}}
def if_(cond, body):      return {"opcode": "if", "inputs": {"condition": cond, "body": body}}
def go_to(x, y):          return {"opcode": "go_to", "inputs": {"x": x, "y": y}}
def point_towards(x, y):  return {"opcode": "point_towards", "inputs": {"x": x, "y": y}}
def turn(deg):            return {"opcode": "turn_degrees", "inputs": {"degrees": deg}}
def move(steps):          return {"opcode": "move_steps", "inputs": {"steps": steps}}
def set_var(n, v):        return {"opcode": "set_var", "inputs": {"name": n, "value": v}}
def change(n, by):        return {"opcode": "change_var", "inputs": {"name": n, "by": by}}
def say(t, size="large"): return {"opcode": "say", "inputs": {"text": t, "size": size}}
def set_color(c):         return {"opcode": "set_color", "inputs": {"color": c}}
def set_size(w, h):       return {"opcode": "set_size", "inputs": {"w": w, "h": h}}
def wait(s):              return {"opcode": "wait_seconds", "inputs": {"seconds": s}}
def stop(mode):           return {"opcode": "stop", "inputs": {"mode": mode}}

def var(n):               return {"opcode": "variable", "inputs": {"name": n}}
def add(a, b):            return {"opcode": "add", "inputs": {"a": a, "b": b}}
def sub(a, b):            return {"opcode": "subtract", "inputs": {"a": a, "b": b}}
def mul(a, b):            return {"opcode": "multiply", "inputs": {"a": a, "b": b}}
def gt(a, b):             return {"opcode": "greater_than", "inputs": {"a": a, "b": b}}
def lt(a, b):             return {"opcode": "less_than", "inputs": {"a": a, "b": b}}
def eq(a, b):             return {"opcode": "equals", "inputs": {"a": a, "b": b}}
def and_(a, b):           return {"opcode": "and", "inputs": {"a": a, "b": b}}
def or_(a, b):            return {"opcode": "or", "inputs": {"a": a, "b": b}}
def not_(a):              return {"opcode": "not", "inputs": {"a": a}}
def touching(name):       return {"opcode": "touching_sprite?", "inputs": {"name": name}}
def random(a, b):         return {"opcode": "random", "inputs": {"from": a, "to": b}}
def mouse_x():            return {"opcode": "mouse_x", "inputs": {}}
def mouse_y():            return {"opcode": "mouse_y", "inputs": {}}
def mouse_down():         return {"opcode": "mouse_down?", "inputs": {}}
def x_pos():              return {"opcode": "x_position", "inputs": {}}
def y_pos():              return {"opcode": "y_position", "inputs": {}}


def any_touching(names):
    """Right-folded OR of touching_sprite? over a list of sprite names."""
    cond = touching(names[-1])
    for n in reversed(names[:-1]):
        cond = or_(touching(n), cond)
    return cond


# ---- constants ------------------------------------------------------------

# Screen / spawn geometry (the runtime's fixed 480x352 play area, sprites 16px).
SCREEN_W, SCREEN_H = 480, 352
OFF = 16                 # spawn / wrap margin (one sprite-width outside the screen)

PLAYER_SPEED = 3
FIRE_COOLDOWN = 0.28     # min seconds between shots while the button is held
BULLET_SPEED = 9
ZOMBIE_SPEED = 0.8

NUM_ZOMBIES = 10
ZOMBIE_NAMES = ["Zombie%d" % i for i in range(1, NUM_ZOMBIES + 1)]
BULLET_NAMES = ["Bullet1", "Bullet2", "Bullet3"]

MAX_HP = 3
BAR_W = 16               # full health-bar width in px (= a full-HP zombie's width)
BAR_H = 3
BAR_DY = 12              # health bar floats this many px above the zombie centre

COL_PLAYER = "#ffffff"
COL_BULLET = "#ffee55"
COL_ZOMBIE = "#6abf4b"
COL_BAR    = "#46d65a"   # health bar green
COL_CLEAR  = "#ffffff00"

PLAYER_HOME = (240, 176)


# ---- Player ---------------------------------------------------------------

def player_script():
    # Movement loop. Each tick we snapshot the position into player_x/player_y (read by the
    # bullets to spawn from the player and by the zombies as their target), then move on WASD.
    # After moving we revert to the snapshot if we ended up inside any zombie, so the player can
    # never walk into one (the wall-resolve pattern from the platformer). Movement is disabled
    # while invincible (the knockback owns the position then).
    wrap = [
        if_(lt(x_pos(), -OFF), [go_to(SCREEN_W + OFF, y_pos())]),
        if_(gt(x_pos(), SCREEN_W + OFF), [go_to(-OFF, y_pos())]),
        if_(lt(y_pos(), -OFF), [go_to(x_pos(), SCREEN_H + OFF)]),
        if_(gt(y_pos(), SCREEN_H + OFF), [go_to(x_pos(), -OFF)]),
    ]
    move_loop = hat([
        set_var("lives", 5),
        set_var("ammo", 3),
        set_var("fire_ready", 0),
        set_var("p_invincible", 0),
        set_var("p_hit", 0),
        set_var("zombie_pause", 0),
        set_var("player_x", PLAYER_HOME[0]),
        set_var("player_y", PLAYER_HOME[1]),
        go_to(*PLAYER_HOME),
        forever([
            set_var("player_x", x_pos()),
            set_var("player_y", y_pos()),
            if_(eq(var("p_invincible"), 0), [
                if_({"opcode": "key_pressed?", "inputs": {"key": "W"}}, [go_to(x_pos(), sub(y_pos(), PLAYER_SPEED))]),
                if_({"opcode": "key_pressed?", "inputs": {"key": "S"}}, [go_to(x_pos(), add(y_pos(), PLAYER_SPEED))]),
                if_({"opcode": "key_pressed?", "inputs": {"key": "A"}}, [go_to(sub(x_pos(), PLAYER_SPEED), y_pos())]),
                if_({"opcode": "key_pressed?", "inputs": {"key": "D"}}, [go_to(add(x_pos(), PLAYER_SPEED), y_pos())]),
                # don't walk into a zombie: revert to this tick's start position
                if_(any_touching(ZOMBIE_NAMES), [go_to(var("player_x"), var("player_y"))]),
            ]),
            *wrap,
        ]),
    ])

    # Fire loop: only arm fire_ready while the mouse button is held, then cool down. A bullet
    # consumes fire_ready (sets it back to 0), so holding the button auto-repeats at FIRE_COOLDOWN.
    fire_loop = hat([
        forever([
            if_(mouse_down(), [
                set_var("fire_ready", 1),
                wait(FIRE_COOLDOWN),
            ]),
        ]),
    ])

    # Hit handler: when a zombie marks p_hit, lose a life, freeze the horde (zombie_pause),
    # knock back away from the hit, blink, then resume. p_invincible stays set across the whole
    # sequence so a single contact can't drain several lives.
    blink = []
    for _ in range(4):
        blink += [move(3), set_color("#000000"), wait(0.05), set_color(COL_PLAYER), wait(0.05)]
    hit_loop = hat([
        forever([
            if_(eq(var("p_hit"), 1), [
                set_var("p_hit", 0),
                set_var("p_invincible", 1),
                set_var("zombie_pause", 1),
                change("lives", -1),
                point_towards(var("hit_from_x"), var("hit_from_y")),
                turn(180),
                *blink,
                set_color(COL_PLAYER),
                set_var("zombie_pause", 0),
                set_var("p_invincible", 0),
            ]),
        ]),
    ])

    # Ammo regen: top back up to 3 a second after running dry.
    ammo_loop = hat([
        forever([
            if_(lt(var("ammo"), 1), [
                wait(1.0),
                set_var("ammo", 3),
            ]),
        ]),
    ])

    return [move_loop, fire_loop, hit_loop, ammo_loop]


# ---- Bullets --------------------------------------------------------------

def bullet_script():
    # Fire when armed and we have ammo: spawn at the player, aim at the cursor, go active.
    fire = if_(
        and_(
            and_(eq(var("active"), 0), gt(var("ammo"), 0)),
            eq(var("fire_ready"), 1),
        ),
        [
            set_var("fire_ready", 0),
            change("ammo", -1),
            go_to(var("player_x"), var("player_y")),
            point_towards(mouse_x(), mouse_y()),
            set_var("active", 1),
        ],
    )

    # Deactivate once the bullet leaves the screen (a generous margin).
    off_screen = or_(
        or_(
            or_(lt(x_pos(), -24), gt(x_pos(), SCREEN_W + 24)),
            lt(y_pos(), -24),
        ),
        gt(y_pos(), SCREEN_H + 24),
    )

    # Damage: a bullet authoritatively decrements the HP of the *first* zombie it overlaps and
    # then deactivates, so a shot always lands exactly one point of damage on one zombie (the
    # `active == 1` guard stops the later ifs from firing once it's spent — no double counting,
    # and no race with the zombie reading the bullet).
    damage = []
    for i, zn in enumerate(ZOMBIE_NAMES, 1):
        damage.append(if_(and_(eq(var("active"), 1), touching(zn)), [
            change("z%d_hp" % i, -1),
            set_var("active", 0),
            go_to(-100, -100),
        ]))

    travel = if_(eq(var("active"), 1), [
        move(BULLET_SPEED),
        if_(off_screen, [set_var("active", 0), go_to(-100, -100)]),
        *damage,
    ])

    return [hat([
        set_var("active", 0),
        go_to(-100, -100),
        forever([fire, travel]),
    ])]


# ---- Zombies --------------------------------------------------------------

def zombie_script(index):
    hp = "z%d_hp" % index
    zx = "z%d_x" % index
    zy = "z%d_y" % index
    others = [n for n in ZOMBIE_NAMES if n != "Zombie%d" % index]

    # Spawn from a random screen edge (e in [0,4) picks top/bottom/left/right), resetting HP.
    spawn = if_(
        and_(
            and_(eq(var("alive"), 0), gt(var("spawn_count"), 0)),
            eq(var("spawn_ready"), 1),
        ),
        [
            set_var("spawn_ready", 0),
            change("spawn_count", -1),
            change("zombies_alive", 1),
            set_var(hp, MAX_HP),
            set_var("e", random(0, 4)),
            if_(lt(var("e"), 1), [go_to(random(-OFF, SCREEN_W + OFF), -OFF)]),
            if_(and_(not_(lt(var("e"), 1)), lt(var("e"), 2)), [go_to(random(-OFF, SCREEN_W + OFF), SCREEN_H + OFF)]),
            if_(and_(not_(lt(var("e"), 2)), lt(var("e"), 3)), [go_to(-OFF, random(-OFF, SCREEN_H + OFF))]),
            if_(not_(lt(var("e"), 3)), [go_to(SCREEN_W + OFF, random(-OFF, SCREEN_H + OFF))]),
            set_var("alive", 1),
        ],
    )

    # Alive: publish position (for the health bar), chase the player while the horde isn't paused,
    # register a hit, then step back out of the player / other zombies. Die when shot to 0 HP.
    alive_body = [
        set_var(zx, x_pos()),
        set_var(zy, y_pos()),
        if_(eq(var("zombie_pause"), 0), [
            point_towards(var("player_x"), var("player_y")),
            move(ZOMBIE_SPEED),
            # touched the player -> mark the hit (the player handler throws itself clear)
            if_(and_(touching("Player"), eq(var("p_invincible"), 0)), [
                set_var("hit_from_x", x_pos()),
                set_var("hit_from_y", y_pos()),
                set_var("p_hit", 1),
            ]),
            # then step back out so we never bury into the player or stack on another zombie
            if_(touching("Player"), [move(-ZOMBIE_SPEED)]),
            if_(any_touching(others), [move(-ZOMBIE_SPEED)]),
        ]),
        if_(lt(var(hp), 1), [
            set_var("alive", 0),
            change("zombies_alive", -1),
            go_to(-200, -200),
            set_var(zx, -300),
            set_var(zy, -300),
        ]),
    ]

    return [hat([
        set_var("alive", 0),
        set_var(hp, MAX_HP),
        set_var(zx, -300),
        set_var(zy, -300),
        go_to(-200, -200),
        forever([spawn, if_(eq(var("alive"), 1), alive_body)]),
    ])]


def healthbar_script(index):
    # Follow the zombie a few px above its centre and draw a green bar whose width tracks HP.
    # When the zombie dies it parks z*_x/z*_y far off-screen, so the bar follows it out of view.
    hp = "z%d_hp" % index
    zx = "z%d_x" % index
    zy = "z%d_y" % index
    return [hat([
        forever([
            go_to(var(zx), sub(var(zy), BAR_DY)),
            set_size(mul(var(hp), BAR_W / MAX_HP), BAR_H),
        ]),
    ])]


# ---- Other sprites --------------------------------------------------------

def lives_hud_script():
    return [hat([forever([say(var("lives"), "large")])])]


def spawner_script():
    # Wave pump: when the screen is clear and nothing is queued, wait, bump the wave and queue
    # (wave + 2) zombies. A second loop pulses spawn_ready so queued zombies trickle in.
    wave = hat([
        set_var("wave", 0),
        set_var("spawn_count", 0),
        set_var("zombies_alive", 0),
        forever([
            if_(and_(eq(var("zombies_alive"), 0), eq(var("spawn_count"), 0)), [
                wait(2.0),
                change("wave", 1),
                set_var("spawn_count", add(var("wave"), 2)),
            ]),
        ]),
    ])
    pulse = hat([
        forever([
            set_var("spawn_ready", 1),
            wait(0.3),
        ]),
    ])
    return [wave, pulse]


def announcer_script():
    return [hat([
        forever([
            if_(lt(var("lives"), 1), [
                go_to(240, 176),
                say("GAME OVER", "large"),
                stop("all"),
            ]),
        ]),
    ])]


# ---- assembly -------------------------------------------------------------

def sprite(name, x, y, w, h, color, script):
    return {"name": name, "x": x, "y": y, "w": w, "h": h, "color": color, "script": script}


def build_sprites():
    sprites = [sprite("Player", PLAYER_HOME[0], PLAYER_HOME[1], 16, 16, COL_PLAYER, player_script())]
    for n in BULLET_NAMES:
        sprites.append(sprite(n, -100, -100, 8, 8, COL_BULLET, bullet_script()))
    for i, n in enumerate(ZOMBIE_NAMES, 1):
        sprites.append(sprite(n, -200, -200, 16, 16, COL_ZOMBIE, zombie_script(i)))
    sprites.append(sprite("LivesHud", 32, 32, 16, 16, COL_CLEAR, lives_hud_script()))
    sprites.append(sprite("Spawner", -400, -400, 16, 16, COL_CLEAR, spawner_script()))
    sprites.append(sprite("Announcer", 240, 176, 16, 16, COL_CLEAR, announcer_script()))
    # Health bars last so they draw on top of the zombies.
    for i in range(1, NUM_ZOMBIES + 1):
        sprites.append(sprite("HealthBar%d" % i, -300, -312, BAR_W, BAR_H, COL_BAR, healthbar_script(i)))
    return sprites


def build_variables():
    g = lambda n, v: {"name": n, "value": v, "scope": "global"}
    variables = [
        g("lives", 5),
        g("ammo", 3),
        g("fire_ready", 0),
        g("player_x", PLAYER_HOME[0]),
        g("player_y", PLAYER_HOME[1]),
        g("p_invincible", 0),
        g("p_hit", 0),
        g("zombie_pause", 0),
        g("hit_from_x", 0),
        g("hit_from_y", 0),
        g("wave", 0),
        g("spawn_count", 0),
        g("spawn_ready", 0),
        g("zombies_alive", 0),
    ]
    # Per-zombie position + HP are globals so the bullets (damage) and health bars (follow/size)
    # can read/write the right zombie's state across sprites.
    for i in range(1, NUM_ZOMBIES + 1):
        variables.append(g("z%d_x" % i, -300))
        variables.append(g("z%d_y" % i, -300))
        variables.append(g("z%d_hp" % i, MAX_HP))
    for n in BULLET_NAMES:
        variables.append({"name": "active", "value": 0, "scope": n})
    for n in ZOMBIE_NAMES:
        variables.append({"name": "alive", "value": 0, "scope": n})
        variables.append({"name": "e", "value": 0, "scope": n})
    return variables


def main():
    project = {
        "background": "#101418ff",
        "grid": {"color": "#87cefa59", "show": True, "snap": True, "step": 8},
        "scripts": build_sprites(),
        "variables": build_variables(),
    }
    with open("zombie.json", "w") as f:
        json.dump(project, f, indent="\t", sort_keys=True)
        f.write("\n")
    print("wrote zombie.json with %d sprites, %d variables"
          % (len(project["scripts"]), len(project["variables"])))


if __name__ == "__main__":
    main()
